services:
  unoserver:
    image: fufuhu/unoserver
    ports:
      - "2003:2003"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - unoserver
    environment:
      - UNOSERVER_HOST=unoserver
      - UNOSERVER_PORT=2003
